# Generated by Django 4.0.3 on 2022-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_editor_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no image', upload_to='images/'),
        ),
    ]
